### ISSUE TITLE
[BUG] Rendering branch fails to compile post FXAA intergration

### ISSUE THREAD

**Issue by PlasmaDev5** [SparkyStudios/ezEngine#5]
**Bug description:**
Looks to be a either missing files issue or a naming issue. No FramePass.h and no FXAAPass.cpp

**Comment by na2axl** [comment]
@PlasmaDev5 the lastest commit should have fixed the issue.

**Comment by PlasmaDev5** [comment]
Get/Set ISO looks to be missing from the camera :) Fixed it locally for now

**Comment by na2axl** [comment]
@PlasmaDev5 thanks for checking, I think the last push fixes thoses issues. I'll push more render passes in the next days, I'm currently working on the Motion Blur.
