### ISSUE TITLE
[DOCS] usage of Deferred renderer pass is unclear

### ISSUE THREAD

**Issue by PlasmaDev5** [SparkyStudios/ezEngine#6]
In the deferred render pass commit its mentioned it works fine in its current state.
Looking at the node its very unclear how its intended to be used because there is nothing to that provides it inputs
and no use for most of its outputs.

**Comment by na2axl** [comment]
The deferred render pass works the same as the forward pass, you should feed him with source passes. You can create source passes as following:

- ColorSource as Albedo using rgba16 or rgbaUByteNorm formats
- NormalSource as Normal using rgba16 format
- MaterialSource as Material using rgba16 format
- VelocitySource as Velocity using rg16 format

For all the sources (depth included) disable the MSAA sample count. I'm not sure it will work with MSAA but you can give it a try.

Once done you should replace the forward render pass with the deferred render pass, as they don't work together at the moment (will need some changes in materials). Then you connect the Output node of the deferred pass to the Color node of the sky render pass.

Other output nodes can be used by some post effects (like the MotionBlur pass which will use the Velocity output) so I've juste let them available.

![image](https://user-images.githubusercontent.com/14062034/210014557-300a1866-af49-4235-a6b0-ad468bcbbbc6.png)

**Comment by PlasmaDev5** [comment]
Thanks for the help on this. in retrospect it should of been easy to work out :D
